name: flutter_lime
description: A text scanner app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

#https://pub.flutter-io.cn/flutter
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  #图片选择器
  image_picker: ^0.6.1
  #可定制相机
  camera:
    git:
      url: git://github.com/kmorkos/plugins.git
      ref: camera/crash-fix
      path: packages/camera/
  #加载动画
  flutter_spinkit: ^3.1.0
  #图片压缩
  image: 2.1.4
  flutter_image_compress: ^0.6.3
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git
  #路径获取
  path_provider: ^0.4.1
  #网络请求库
  dio: 2.1.13
  #toast
  fluttertoast: ^3.0.0 #3.1.0在ios上弹出新页面后，无法再显示toast
  #  fluttertoast:
  #    git: https://github.com/PonnamKarthik/FlutterToast.git
  #sp
  shared_preferences: ^0.5.3
  #数据库
  sqflite: ^1.1.6
  #语音库
  flutter_tts: ^0.2.6
  #打开其他 软件
  url_launcher: ^5.1.1
  #加密算法 如sha256
  crypto: 2.0.6
  #软件包信息
  package_info: ^0.4.0+6
  #material颜色选择器
  flutter_material_color_picker: ^1.0.3
  #内容分享
  share: ^0.6.2+1
  #状态机
  provide: ^1.0.2
  #返回键监听
  back_button_interceptor: ^4.0.6
  #图片拖动缩放
  flutter_drag_scale:
    git: https://github.com/LiuC520/flutter_drag_scale.git
  #获取相册图片
  #  photo_provider: ^0.1.0
  #下拉刷新、上拉加载
  flutter_easyrefresh: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/logo.png
    - images/placeholder.png

  fonts:
    - family: iconfont
      fonts:
        - asset: fonts/iconfont.ttf